- AI Tools:
    - ChatGPT:
        - abbr: GPT
          icon: openai
          href: https://chatgpt.com/
    - OpenAI Playground:
        - abbr: PLAY
          icon: openai
          href: https://platform.openai.com/playground/chat
    - Google Gemini:
        - abbr: GEM
          icon: google
          href: https://gemini.google.com
- Development:
    - GitHub:
        - abbr: GH
          icon: github
          href: https://github.com/
- Social & Content:
    - YouTube:
        - abbr: YT
          icon: youtube
          href: https://youtube.com
    - Reddit:
        - abbr: RE
          icon: reddit
          href: https://reddit.com
    - Medium:
        - abbr: MED
          icon: medium
          href: https://medium.com/me/stories/public
    - Twitter:
        - abbr: X
          icon: twitter
          href: https://x.com/pedroanisio
- Media Management:
    - ThinLinc:
        - abbr: TLC
          href: https://45-91-208-9.a.seedbox.vip:300/agent
- Family & Personal:
    - OneDrive:
        - abbr: OD
          href: https://onedrive.live.com/
    - Google Calendar:
        - abbr: CAL
          href: https://calendar.google.com/
- Production:
    - NTFY:
        - abbr: NTF
          href: http://grid-guard-hub-1.vm.lab.internal:8081
    - cAdvisor:
        - abbr: ADV
          href: http://grid-guard-hub-1.vm.lab.internal:8080/containers/
    - Grafana:
        - abbr: GRF
          href: http://grid-guard-hub-1.vm.lab.internal:3030/?orgId=1
- Datasets & Archives:
    - Medium:
        - abbr: MED
          href: https://medium.com/me/stories/public
    - Twitter:
        - abbr: X
          href: https://x.com/pedroanisio
    - DIBRARQ:
        - abbr: DIB
          href: https://dibrarq.arquivonacional.gov.br/
    - Arquivo SP:
        - abbr: ASP
          href: https://atom.saa.sp.gov.br/
- Products & Tools:
    - Quivr:
        - abbr: QVR
          href: https://www.quivr.app/
    - Beam:
        - abbr: BM
          href: https://www.beam.app/
    - OpenArt:
        - abbr: OA
          href: https://openart.ai
    - Picofme:
        - abbr: PIC
          href: https://picofme.io