---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- IoT:
    - Home Assistant:
        icon: home-assistant.png
        href: https://6xv5wc086hefbwqxijcm4jogumejd6mv.ui.nabu.casa/
        description: Homeassistant

- Networking:
    - Switch TP-Link:
        icon: mdi-lan-#FFFFFF
        href: http://10.0.0.14/
        description: Switch TP-Link

    - Switch MikroTik:
        icon: mdi-lan-#FFFFFF
        href: http://10.0.0.172/    
        description: Switch (MikroTik) CSS610-8G-2S+      

    - Tailscale Admin:
        icon: mdi-folder-key-network-#FFFFFF
        href: https://login.tailscale.com/admin
        description: Tailscale Admin  

    - UniFI Admin:
        icon: mdi-wifi-settings-#FFFFFF
        href: https://unifi.ui.com/
        description: (internet) UniFI Admin   

- Services:
    - pve-mngt-1:
        icon: proxmox-light.svg
        href: https://192.168.199.2:8006
        ping: 192.168.199.2
        description: manegment server.
        widget:
            type: proxmox
            url: https://192.168.199.2:8006
            username: api@pve!homepage
            password: 50a1e832-9439-48e5-a858-b740f8892d5c
            node: pve-mngt-1

    - pve-node-1:
        icon: proxmox-light.svg
        href: https://pve-node-1.tailc357aa.ts.net:8006
        ping: pve-node-1.tailc357aa.ts.net
        description: pve-node-1 server.
        widget:            
            url: https://pve-node-1.tailc357aa.ts.net:8006
            type: proxmox
            username: api@pve!homepage
            password: 71536307-4d82-422f-8eb2-eb4eb48b36dc
            node: pve-node-1

    - pve-storage-1:
        icon: proxmox-light.svg
        href: https://192.168.199.10:8006
        ping: 192.168.199.10
        description: pve-storage-1 server.
        widget:
            url: https://192.168.199.10:8006
            type: proxmox
            username: api@pve!homepage
            password: 91119d5f-9085-4443-bb93-a30242deafa4
            node: pve-storage-1

    - Portainer:
        icon: portainer.png
        href: https://portainer.local.arc4d3.io/
        ping: 10.10.10.5
        description: Portainer Container Management

    - Jupyter:
        icon: jupyter.png
        href: https://jupyter.local.arc4d3.io/
        ping: 10.10.10.10
        description: Jupyter Notebook

    - GitLab:
        icon: gitlab.png
        href: https://gitlab.local.arc4d3.io/
        ping: 10.10.10.10
        description: GitLab Community Edition

