---
# For configuration options and examples, please see:
# https://gethomepage.dev/latest/configs/services

- IoT:
    - Home Assistant:
        icon: home-assistant.png
        href: https://6xv5wc086hefbwqxijcm4jogumejd6mv.ui.nabu.casa/
        description: Homeassistant

- Networking:
    - Switch TP-Link:
        icon: mdi-lan-#FFFFFF
        href: http://10.0.0.14/
        description: Switch TP-Link

    - Switch MikroTik:
        icon: mdi-lan-#FFFFFF
        href: http://10.0.0.172/    
        description: Switch (MikroTik) CSS610-8G-2S+      

    - Tailscale Admin:
        icon: mdi-folder-key-network-#FFFFFF
        href: https://login.tailscale.com/admin
        description: Tailscale Admin  

    - UniFI Admin:
        icon: mdi-wifi-settings-#FFFFFF
        href: https://unifi.ui.com/
        description: (internet) UniFI Admin   

- Proxmox:
    - pve-node-0:
        icon: proxmox.png
        href: https://192.168.199.102:8006
        description: Proxmox Virtual Env (FILESERVER)
        ping: 192.168.199.102
        node: pve-node-0
        widget:
          type: proxmox
          url: https://192.168.199.102:8006
          username: api@pam!ro
          password: 079d7317-1b2c-4b83-8642-5caa886dc48b 

    - pve-node-1:
        icon: proxmox.png
        href: https://192.168.199.103:8006
        description: Proxmox Virtual Env (NUC-02)
        ping: 192.168.199.103
        node: pve-node-1
        widget:
          type: proxmox
          url: https://192.168.199.103:8006
          username: api@pam!ro
          password: 079d7317-1b2c-4b83-8642-5caa886dc48b

    - pve-node-3:
        icon: proxmox.png
        href: https://192.168.199.104:8006
        description: Proxmox Virtual Env (ROG)
        ping: 192.168.199.104
        widget:
          type: proxmox
          node: pve-node-3
          url: https://192.168.199.104:8006
          username: api@pam!ro
          password: 079d7317-1b2c-4b83-8642-5caa886dc48b

    - pve-node-4:
        icon: proxmox.png
        href: https://192.168.199.105:8006
        description: Proxmox Virtual Env (WHITE)
        ping: 192.168.199.105
        widget:
          type: proxmox
          node: pve-node-4
          url: https://192.168.199.105:8006
          username: api@pam!ro
          password: 079d7317-1b2c-4b83-8642-5caa886dc48b

    - pbs-01:
        icon: proxmox.png
        href: https://10.10.10.105:8007
        description: Proxmox Backup Server 01
        ping: 10.10.10.105
        widget:
          type: proxmoxbackupserver
          url: https://10.10.10.105:8007
          username: api@pbs!ro
          password: f2825bb2-b299-456c-aa8f-eebfb39e2bfb    

- Services:
    - Portainer:
        icon: portainer.png
        href: https://portainer.local.arc4d3.io/
        description: Portainer Container Management

    - OPNsense:
        icon: opnsense.png
        href: https://10.10.10.1/
        description: OPNsense Firewall

    - Jupyter:
        icon: jupyter.png
        href: https://jupyter.local.arc4d3.io/
        description: Jupyter Notebook

    - GitLab:
        icon: gitlab.png
        href: https://gitlab.local.arc4d3.io/
        description: GitLab Community Edition

