---
# For configuration options and examples, please see:
# https://gethomepage.dev/configs/settings/
# Title of the homepage
title: "PALS - lab.internal"

# URL where the homepage starts
startUrl: "/"

# Enable card background blur for aesthetics
cardBlur: md

theme: dark
color: slate

# Background image and filters
background:
  image: https://cdn.wallpapersafari.com/25/37/aMvXOf.jpg 
  blur: lg
  saturate: 90
  brightness: 60
  opacity: 80

# Page layout configuration
layout:
  Servers:
    style: column
    columns: 4
  Applications:
    style: row
    columns: 3

# Custom favicon for your page
favicon: https://rockettheme.com/favicon.png 

# Quick launch settings
quicklaunch:
  searchDescriptions: true
  hideInternetSearch: true
  showSearchSuggestions: true
  hideVisitURL: true
  provider: google
